version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_UPLOAD_URL=http://localhost:5000/uploads
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    volumes:
      - ./admin:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/autoani
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-this-in-production
      - UPLOAD_PATH=/app/uploads
      - CLIENT_URL=http://localhost:3000
      - ADMIN_URL=http://localhost:3001
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads-data:/app/uploads

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=autoani
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - uploads-data:/var/www/uploads
    depends_on:
      - frontend
      - admin
      - backend

volumes:
  mongo-data:
  uploads-data:
